### ISSUE TITLE
Apply syntax highlighting based on file extension

### ISSUE THREAD

**Issue by devkeydet** [harrydowning/vscode-yaml-embedded-languages#36]
Have you considered providing syntax highlighting based on file extension?  For example, if I wanted all *.pa.yaml files to have formatting everywhere without manually having to add `# powerfx` within every property.

**Comment by harrydowning** [comment]
I have thought about doing something like this. Not exactly as you suggest, but maybe something like having comments to turn on/off highlighting within properties for the rest of the file or until the next comment. For your case you could specify the language once at the top of the file. Maybe it would looke something like
```yaml
# yaml-embedded-languages: powerfx <- turns on powerfx highlighting until EOF or next comment
example:
  ...
# yaml-embedded-languages: off/none <- turns off highlighting
example:
  ...
# yaml-embedded-languages: python <- turns on python highlighting
example:
  ...
```
I'm not sure how hard this would be.
