### ISSUE TITLE
Support for Nested Embedded Languages

### ISSUE THREAD

**Issue by meehanman** [harrydowning/vscode-yaml-embedded-languages#56]
Hey,

Maybe it's a bug, or maybe it's a feature request but when having the format:

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  mo-yaml.yaml: | # yaml
    key1: hello
    key2: world
    code: | # lua
        -- This is a lua comment
        local greating = "Hello World"
        print(greeting)
    key4: true
```

I do get the inner `mo-yaml.yaml` key contents parsed as yaml but when it comes to the `code:` section. I'd expect this to be highlighted as `lua` but instead it's treated as yaml text.

![image](https://github.com/user-attachments/assets/c064d007-4ccf-46ff-84ad-b161ece73a8b)

It would be good if we can have the parsing keep working as we are nesting (or enable a max nest if there issues with recursion)
